/*!
 * \defgroup  applicationModule Application Modules section
 * 
 */


/*!
 * \defgroup  definitions Application Constants
 * 
 * \ingroup applicationModule
 */


/*!
 * \defgroup  libraryModules Library Modules Used in the Application.
 */


/*!
 * \mainpage
 *
 * # Overview
 *
 * This Firmware implements the functions of the FW301 Power Service 
 * software specification.
 * 
 * 
 * # Dependencies 
 * 
 * The Application has been developed with the use of the Microchip Harmony 3
 * libraries. The libraries are a set of source files auto generated by the 
 * Harmony 3 configurator tools and contained into the following directories:
 * - src/config;
 * - src/packs;
 * 
 * ***NOTE: those directories shall never be directly modified since 
 * they are auto-rigenerated every time the generator tool is launched.*** 
 *
 * The libraries make use of the CMSIS 5.4.0 for ARM processors
 * and SAME51_DFP 3.6.130
 *  
 * 
 * # Modules
 *
 * The Application implements the following modules:
 * - @ref applicationModule : defines common objects to the application modules;
 * - @ref busHwModule : module implementing the Bus Hardwar control;
 * - @ref generatorModule : module implementing the Generator Interface control;
 * - @ref protocolModule : module implementing CAN communication protocol;
 * - @ref libraryModules : this is the set of the libraries used in the current application;
 *
 * # Compilation
 * 
 * This software is compiled with the MPLAB-X IDE 5.50:
 * - Compiler: XC32 Vs 3.1
 * 
 * 
 * # Licensing
 *
 * The Application has been developed with the Microchip Harmony 3 libraries 
 * with the Microchip License Agreement conditions as described in:
 * - @ref licenseAgreement 
 *
 * # Documentation
 * 
 * This documentation has been produced with Doxygen 
 */



#ifndef _APPLICATION_H    /* Guard against multiple inclusion */
#define _APPLICATION_H

// Defines the Application revision code

/** \addtogroup definitions
 *  @{
*/
#define _BOOTLOADER_REV_MAJ 0
#define _BOOTLOADER_REV_MIN 1
#define _BOOTLOADER_REV_SUB 1


#define _BOOTLOADER_APPLICATION_BOOT 0x2000
#define _BOOTLOADER_SHARED_RAM 0x20000000
        
#define _BOOT_ACTIVATION_CODE_PRESENCE0 0x11
#define _BOOT_ACTIVATION_CODE_PRESENCE1 0x82
#define _BOOT_ACTIVATION_CODE_PRESENCE2 0x13
#define _BOOT_ACTIVATION_CODE_PRESENCE3 0x84

#define _BOOT_ACTIVATION_CODE_START0 0x1
#define _BOOT_ACTIVATION_CODE_START1 0x2
#define _BOOT_ACTIVATION_CODE_START2 0x3
#define _BOOT_ACTIVATION_CODE_START3 0x4


typedef struct{
    uint8_t activation_code0;
    uint8_t activation_code1;
    uint8_t activation_code2;
    uint8_t activation_code3;

    uint8_t boot_maj;
    uint8_t boot_min;
    uint8_t boot_sub;
    uint8_t app_maj;
    uint8_t app_min;
    uint8_t app_sub;

    uint8_t sp0;
    uint8_t sp1;
    uint8_t sp2;
    uint8_t sp3;
    uint8_t sp4;
    uint8_t sp5;

}_BOOTLOADER_SHARED_t;

/** @}*/
        
#endif 