format_version: v1.0
configName: PCB301_Bootloader
folderName: FW_BOOT
frameworkPath: C:\Users\marco\Harmony3
processor: ATSAME51J20A
projectName: FW_BOOT
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.7.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\SAME51_DFP\3.4.98\atdf\ATSAME51J20A.atdf
