format_version: v1.0
type: UniqueComponent
attributes: {id: can1}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: CALCULATED_NOMINAL_BITRATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can1, value: '1000'}
  - type: String
    attributes: {id: CALCULATED_NOMINAL_ERRORRATE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can1, value: '0.000'}
  - type: Menu
    attributes: {id: CAN1_STD_FILTER1}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: enabled}
        children:
        - {type: Value, value: 'true'}
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: CAN1_STD_FILTER1_SFID1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '80'}
  - type: Hex
    attributes: {id: CAN1_STD_FILTER1_SFID2}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1792'}
  - type: Integer
    attributes: {id: CAN_CORE_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can1, value: '60000000'}
  - type: Comment
    attributes: {id: CAN_CORE_CLOCK_INVALID_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Comment
    attributes: {id: CAN_TIME_QUANTA_INVALID_COMMENT}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
  - type: Integer
    attributes: {id: FILTERS_STD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: FILTERS_STD_REJECT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Integer
    attributes: {id: NBTP_NSJW}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can1, value: '15'}
  - type: Integer
    attributes: {id: NBTP_NTSEG1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can1, value: '44'}
  - type: Integer
    attributes: {id: NBTP_NTSEG2}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can1, value: '15'}
  - type: Integer
    attributes: {id: NBTP_TOTAL_TIME_QUANTA}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can1, value: '60'}
  - type: Integer
    attributes: {id: NOMINAL_BITRATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1000'}
  - type: String
    attributes: {id: NOMINAL_TIME_QUANTA_PERIOD}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: can1, value: '16.667'}
  - type: Boolean
    attributes: {id: RXF1_USE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: TIMESTAMP_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: TIMESTAMP_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Boolean
    attributes: {id: TX_PAUSE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Menu
    attributes: {id: rxf1menu}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'false'}
- type: ElementPosition
  attributes: {x: '152', y: '167', id: can1}
